name: titanic_mlproject
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - pandas>=1.5.0
      - numpy>=1.23.0
      - scikit-learn>=1.2.0
      - mlflow==2.19.0
